reformat and rearrange code
gradebooklet/gradebooklet-web pull request #1
Opened 2021-10-29 07:37 UTC by noahschoenthal

Code gets rearranged and a cleanup

2021-10-29 08:53 UTC, noahschoenthal commented on src/main.js
> +import { I18N, TCustomAttribute } from 'aurelia-i18n';
@luca-bruegger Please consider writing spaces between those curly braces.

2021-10-29 16:27 UTC, luca-bruegger commented on src/main.js
> +import { I18N, TCustomAttribute } from 'aurelia-i18n';
Sure. I will.

2021-10-29 16:31 UTC, luca-bruegger requested changes
PR is on a good path. Still some things u need to fix 🚀

2021-10-29 16:31 UTC, luca-bruegger commented on src/app.css
> +.footer>div {
@noahschoenthal please undo this. Looks a lot cleaner to me, with a space in between.

2021-10-29 16:31 UTC, luca-bruegger commented on src/app.css
> +.download-button>a {
Here aswell

2021-10-29 16:31 UTC, luca-bruegger commented on src/app.css
> +.download-button>a>svg:before {
Same here. Please fix it everywhere.

2021-10-29 16:31 UTC, luca-bruegger commented on src/app.css
> +
Good point. But move the comment above the css selector.

2021-10-30 12:17 UTC, noahschoenthal commented on src/app.css
> +
@luca-bruegger Look at the newly pushed comment does it meet your expectations?

2021-10-30 19:42 UTC, luca-bruegger approved these changes

2021-10-30 19:50 UTC, merged