improve color management and design
gradebooklet/gradebooklet-web pull request #2
Opened 2021-10-29 11:53 UTC by noahschoenthal

2021-10-29 16:42 UTC, luca-bruegger requested changes
Looks good. Some things left. DO NOT MERGE THE package-lock.json.

2021-10-29 16:42 UTC, luca-bruegger commented on src/app.css
> +  --primary-comingsoon: rgb(127, 51, 51);
That's a no-no. Primary variables are here to define things once; Please remove the duplicate assignments like `--primary-coming-soon` and `--primary-gradebooklet`. For further clarification, call the variable: `--secondary-content: rgb(127, 51, 51);` then `--primary-content: rgb(119, 35, 35);` as well as the third one `--tertiary-content: rgb(217, 52, 52, 1);`

2021-10-29 16:42 UTC, luca-bruegger commented on src/app.css
>  }
Please do not work with ids in this specific case. Fix it like this (and keep in mind that you have to do this for `secondary` and `tertiary` colors aswell):
`
.primary-content {
   background-color: var(--primary-content);
}
`

2021-10-29 16:42 UTC, luca-bruegger commented on src/app.css
>    fill: transparent;
No-no again. Define a variable and use it over here.

2021-10-29 16:42 UTC, luca-bruegger commented on src/app.html
> +      <div id="home-gradebooklet" class="swiper-slide">
My bad that i've used id's. But since that's long ago I learnt more and now I recommend to use the classes, we defined above.

2021-10-30 13:07 UTC, noahschoenthal commented on src/app.html
> +      <div id="home-gradebooklet" class="swiper-slide">
@luca-bruegger yeah solved it using class look in new pushed comment.

2021-10-30 19:41 UTC, luca-bruegger approved these changes

2021-10-30 19:48 UTC, merged